from __future__ import annotations

from pathlib import Path

SHIM_TEMPLATE = '''"""Hermes Local Memory plugin shim.

Generated by hermes-local-memory. This file is intentionally tiny: it adds the
project package to sys.path and registers LocalMemoryProvider with Hermes.
"""

from __future__ import annotations

import sys
from pathlib import Path

PACKAGE_ROOT = Path({package_root!r})
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from hermes_local_memory import LocalMemoryProvider  # noqa: E402


def register(ctx):
    ctx.register_memory_provider(LocalMemoryProvider())
'''


def render_plugin_shim(*, package_root: str | Path) -> str:
    """Render a Hermes user-plugin shim for this checkout.

    The shim can live under ``$HERMES_HOME/plugins/local_memory/__init__.py``.
    Hermes' memory plugin discovery imports it and calls ``register(ctx)``.
    """
    resolved_package_root = Path(package_root).expanduser().resolve()
    return SHIM_TEMPLATE.format(package_root=str(resolved_package_root))


def write_plugin_shim(plugin_dir: str | Path, *, package_root: str | Path) -> Path:
    """Write the Hermes plugin shim and return its ``__init__.py`` path."""
    target_dir = Path(plugin_dir).expanduser()
    target_dir.mkdir(parents=True, exist_ok=True)
    shim_path = target_dir / "__init__.py"
    shim_path.write_text(render_plugin_shim(package_root=package_root), encoding="utf-8")
    return shim_path
